/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author jorup
 */
public class InitialView extends javax.swing.JFrame {
    private static final int TIEMPO = 30;
    private int progreso = 0;
    private Timer timer;

    /**
     * Creates new form InitialView1
     */
    public InitialView() {
        initComponents();
        fondo.setIcon(new ImageIcon(((new ImageIcon(getClass().getResource("/img/background/intro.png"))).getImage()).getScaledInstance(620, 370, java.awt.Image.SCALE_SMOOTH)));
        
        // Temporizador para simular la carga
        timer = new Timer(TIEMPO, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                progreso++;
                progressBar.setValue(progreso);

                // Detener el temporizador cuando llega al 100%
                if (progreso >= progressBar.getMaximum()) {
                    timer.stop();
                    cargaCompletada();
                }
            }
        });

        // Inicia el temporizador
        timer.start();
    }
    
    public void cargaCompletada(){
        ControladorVentanas.instance.abrirCerrarMainView(this, true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 330, 20));

        fondo.setForeground(new java.awt.Color(51, 0, 51));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background/intro.png"))); // NOI18N
        fondo.setText("jLabel1");
        fondo.setPreferredSize(new java.awt.Dimension(620, 370));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
