/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Equipo;
import model.Jugador;
import model.TipoJugador;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jorup
 */

public class MainView extends javax.swing.JFrame {
    private Equipo equipo;
    private List<Jugador> jugadores;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        initEquipo();
        personalizarComponentes();
    }
    
    private void initEquipo() {
        // Inicializar equipo y jugadores
        jugadores = new ArrayList<>();
        jugadores.add(new Jugador("Jose", 21, 5, 80, 10, TipoJugador.DEFENSA));
        jugadores.add(new Jugador("Carlos", 23, 7, 85, 9, TipoJugador.MEDICAMPISTA));
        jugadores.add(new Jugador("Luis", 19, 10, 78, 8, TipoJugador.DELANTERO));
        equipo = new Equipo("Ceuta FC", "Guardiola", new ArrayList<>(jugadores));
    }
    
    private void personalizarComponentes() {
        // Configurar el botón buscar
        listarJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlJugadores = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txBuscar.setText("Buscar...");
        getContentPane().add(txBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));
        getContentPane().add(pnlJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 310, 150));

        Nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background/file.png"))); // NOI18N
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background/fondo1.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String textoBuscado = txBuscar.getText();
    
        // Limpiar el panel antes de mostrar nuevos resultados
        pnlJugadores.removeAll();

        // Buscar lista de jugadores que coinciden con el texto
        List<Jugador> listaBuscada = buscarJugadores(textoBuscado);
        if (!listaBuscada.isEmpty()) {
            for (Jugador jugador : listaBuscada) {
                // Crear una etiqueta con el jugador y personalizarla
                JLabel lblJugador = new JLabel(jugador.toString());
                lblJugador.setBorder(BorderFactory.createLineBorder(Color.BLACK)); // Borde negro
                lblJugador.setOpaque(true); // Necesario para establecer un color de fondo
                lblJugador.setBackground(Color.LIGHT_GRAY); // Fondo gris claro
                lblJugador.setFont(new Font("Arial", Font.PLAIN, 14)); // Fuente personalizada
                lblJugador.setPreferredSize(new Dimension(300, 30)); // Ajustar tamaño de las etiquetas

                pnlJugadores.add(lblJugador); // Agregar al panel
            }
        } else {
            // Mostrar un mensaje si no hay resultados
            JLabel lblNoResultados = new JLabel("No se encontraron jugadores con ese nombre.");
            lblNoResultados.setFont(new Font("Arial", Font.ITALIC, 14)); // Texto en cursiva
            lblNoResultados.setForeground(Color.RED); // Texto rojo
            pnlJugadores.add(lblNoResultados);
        }

        // Actualizar el panel para reflejar los cambios
        pnlJugadores.revalidate();
        pnlJugadores.repaint();
    }//GEN-LAST:event_btnBuscarActionPerformed

     private void listarJugadores() {
        pnlJugadores.removeAll();
        for (Jugador jugador : jugadores) {
            JLabel lblJugador = new JLabel(jugador.toString());
            pnlJugadores.add(lblJugador);
        }
        pnlJugadores.revalidate();
        pnlJugadores.repaint();
    }
    
    public Jugador buscarJugador(String nombre) {
        for (Jugador jugador : jugadores) {
            if (jugador.getNombre().equalsIgnoreCase(nombre)) {
                return jugador;
            }
        }
        return null; // Si no encuentra el jugador
    }

    public List<Jugador> buscarJugadores(String nombre) {
        List<Jugador> resultado = new ArrayList<>();
        for (Jugador jugador : jugadores) {
            if (jugador.getNombre().equalsIgnoreCase(nombre)) {
                resultado.add(jugador);
            }
        }
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel pnlJugadores;
    private javax.swing.JTextField txBuscar;
    // End of variables declaration//GEN-END:variables
}
